/*jslint node: true */
/*jslint todo: true */
'use strict';

var textHelper = {
    defaultResponse: 'Please be patient as I learn a new skill.',
    failedResponse: 'I\'m sorry. There was a problem processing this request. Check the Alexa card for details. Goodbye.',
    setupPrompt: 'Welcome to Code Camp 2016.2!',
    help: 'This is the text of available help.',
    simpleHelp: 'This is the simple help.',
    goodbye: 'Thank you for talking with me. Goodbye.',

    nothingToSave: 'There is nothing to save.',
    nothingToFind: 'There is nothing to find.',
    saveError: 'Unable to add/update item.',
    retrieveError: 'Unable to retrieve item.',

    join: function (list, property, conjunction, prefix) {
        var i, name, names = [], nameList = '', separator = prefix ? '.' : ',';
        if (!conjunction) {
            conjunction = 'or';
        }
        if (!property) {
            property = 'speaker';
        }

        for (i = 0; i < list.length; i += 1) {
            // accept an array of names or an array of objects with a speaker property
            if (typeof list[i] === 'object' && property !== undefined) {
                name = list[i][property];
            } else {
                name = list[i];
            }
            if (names.indexOf(name) === -1 && name !== '') {
                names.push(name);
            }
        }

        for (i = 0; i < names.length; i += 1) {
            if (i > 0 && i === names.length - 1) {
                nameList += separator + ' ' + conjunction;
            } else if (i > 0) {
                nameList += separator;
            }
            if (prefix) {
                if (i > 0) {
                    nameList += ' ';
                }
                nameList += prefix + ' ' + (i + 1).toString() + ' is ';
            }
            nameList += ' ' + names[i];
        }

        return nameList;
    },

    speakerNotFound: function (name) { return name === 'unknown' ? 'I did not understand who you said.' : 'I heard you say ' + name + ' but I could not find that name.'; },
    roomNotFound: function (room) { return room === 'unknown' ? 'I did not understand what room you said.' : 'I heard you say ' + room + ' but I could not find that room.'; },
    timeNotFound: function (time) { return time === 'unknown' ? 'I did not understand what time you said.' : 'I heard you say ' + time + ' but I could not find that time.'; },
    whichSpeaker: function (cnt, name) { return 'I found ' + cnt.toString() + ' speakers matching ' + name + '. Which speaker do you want'; },
    speakingAtCountSessions: function (cnt, name) { return name + ' is speaking at ' + cnt.toString() + ' session' + (cnt === 1 ? '' : 's') + '. '; },
    countSessionsMatchingPhrase: function (cnt, phrase) { return 'There are ' + cnt.toString() + ' session' + (cnt === 1 ? '' : 's') + ' matching ' + phrase + '. '; },
    speakersWithBadge: function (badge, list) { return badge === 'unknown' ? 'I did not understand what badge you said.' : badge + ' presenters are ' + this.join(list, 'speaker', 'and') + '.'; },
    isNotHere: function (name) { return name === 'unknown' ? 'I did not understand who you said.' : 'Sorry, ' + name + ' is not presenting today.'; },
    presentationWhenWhere: function (presentation) { return 'There is a presentation on ' + presentation.session_name + ' at ' + presentation.session_time + ' in room ' + presentation.room + '.'; },
    profileNotUpdated: function (name) { return name === 'unknown' ? 'I did not understand who you said.' : name + ' did not update their profile information.'; },
    nextSessionTime: function (time) { return 'The next session is at ' + time + '.'; },
    sessionsNotFound: function (phrase) { return phrase === 'unknown' ? 'I did not understand what session you said.' : 'There are no session matching ' + phrase + '.'; },

    speakerList: [
        'Alex',
        'Alex Grinberg',
        'Amanda',
        'Amanda Lange',
        'Atley',
        'Atley Hunter',
        'Ben',
        'Benjamin',
        'Benjamin Zale',
        'Brackel',
        'Brent',
        'Brent Schooley',
        'Brian',
        'Brian Minisi',
        'Cappelletti',
        'Chabria',
        'Chakraborty',
        'Chris',
        'Chris Gomez',
        'Chris Love',
        'Dale',
        'Dan',
        'Dan Hartshorn',
        'Dane',
        'Dane Morgridge',
        'Darko',
        'Dave',
        'Dave Wentzel',
        'David',
        'David Horvath',
        'David Patrick',
        'David Voyles',
        'Dollard',
        'Ed',
        'Eduard',
        'Eduard Kremer',
        'Eric',
        'Eric Furry',
        'Furry',
        'Georgian',
        'Georgian Grigore',
        'Goff',
        'Goldman',
        'Gomez',
        'Grigore',
        'Grinberg',
        'Hartshorn',
        'He',
        'Henry',
        'Henry He',
        'Horvath',
        'Hunter',
        'Iqbal',
        'Iqbal Khan',
        'Jason',
        'Jason van Brackel',
        'Jen',
        'Jennifer',
        'Jennifer Kenderdine',
        'Joe',
        'Joe Darko',
        'John',
        'Jon',
        'Jon Goldman',
        'Joy',
        'Joy Chakraborty',
        'Karl',
        'Karl Shifflett',
        'Kathleen',
        'Kathleen Dollard',
        'Kathy',
        'Kay',
        'Ken',
        'Ken Dale',
        'Ken Lovely',
        'Kenderdine',
        'Kern',
        'Kevin',
        'Kevin Goff',
        'Khan',
        'Korick',
        'Kremer',
        'Lange',
        'Leonard',
        'Love',
        'Lovely',
        'Mandy',
        'Marcus',
        'Marcus Kern',
        'Mason',
        'Mason Wheeler',
        'Matt',
        'Matt Silva',
        'Melusky',
        'Michael',
        'Michael Montgomery',
        'Mike',
        'Mike Melusky',
        'Mike Yeager',
        'Minisi',
        'Montgomery',
        'Morgridge',
        'Okade',
        'Patrick',
        'Ravi',
        'Ravi Okade',
        'Rich',
        'Rich Ross',
        'Rick',
        'Rick Wargo',
        'Ross',
        'Schooley',
        'Scott',
        'Scott Kay',
        'Shifflett',
        'Silva',
        'Snyder',
        'Stachu',
        'Stachu Korick',
        'Stephen',
        'Stephen Leonard',
        'Steve',
        'TJ',
        'TJ Cappelletti',
        'Todd',
        'Todd Snyder',
        'Voyles',
        'Wargo',
        'Wentzel',
        'Wheeler',
        'Yash',
        'Yash Chabria',
        'Yeager',
        'Zale'
    ],
    badgeList: [ 'MS', 'MVP', 'Microsoft' ],
    roomList: [
        '30th Street',
        'EBC',
        'MPR1',
        'MPR2',
        'MPR3',
        'Berwyn',
        'Malvern',
        'Merion',
        'Paoli',
        'Strafford',
        'Wynnewood'
    ],
    timeList: [
        '08:30am',
        '10:00am',
        '11:30am',
        '01:30pm',
        '03:00pm'
    ],
    sessionPhrases: [
        'dot Net',
        'dot Net Developers',
        'AI',
        'ASP',
        'ASP dot Net',
        'ASP dot Net Core',
        'ASP dot Net Developers',
        'Advanced',
        'Advanced FrontEnd',
        'Advanced FrontEnd Debugging',
        'Alexa',
        'Alexa Skill',
        'Analysis',
        'Analytics',
        'Analytics and Data',
        'Analytics and Data Science',
        'Analyzers',
        'AndroidLinux',
        'Angular',
        'Angular 2',
        'Angular 2 Testing',
        'Angular 2 Testing Strategies',
        'Angular 2 for ASP',
        'AngularJS',
        'AngularJS 1.5.x',
        'AngularJS 1.5.x Componentbased',
        'AngularJS 1.5.x Componentbased Applications',
        'Animation',
        'Animation Make',
        'Animation Make your Mobile',
        'Anyone',
        'Anyone can build',
        'Anyone can build games',
        'App',
        'App Stand',
        'App Stand Out',
        'App with ASP',
        'Application',
        'Application Developers',
        'Application Developers Attendees',
        'Application Developers Attendees chose',
        'Applications',
        'Applications Never',
        'Applications Never Felt',
        'Applications Never Felt So',
        'Apps',
        'Apps with Distributed',
        'Apps with Distributed Caching',
        'Architecting',
        'Architecting Distributed',
        'Architecting Distributed Analytics',
        'Architectures',
        'Architectures with Microsoft',
        'Architectures with Microsoft Azure',
        'Attendees',
        'Attendees chose',
        'Awesomeness',
        'Azure',
        'Azure DevTest',
        'Azure DevTest Labs',
        'Azure Functions',
        'Azure SQL',
        'Azure SQL Database',
        'Azure Service',
        'Azure Service Fabric',
        'Azure Web',
        'Azure Web App',
        'AzureBigData',
        'AzureBigData Technologies',
        'Better',
        'Better C#',
        'Better C# Code',
        'Big',
        'Big Data',
        'Big Data and Hadoop',
        'Boo',
        'Boo Programmable',
        'Boo Programmable Programming',
        'Bot',
        'Build',
        'Build a Bot',
        'Building',
        'Building websites',
        'Building websites on azure',
        'C#',
        'C# Code',
        'C# Code With Live',
        'C# and SQL',
        'C# and SQL Server',
        'CLR',
        'CONVERTIMPLICIT',
        'CONVERTIMPLICIT is a hidden',
        'Caching',
        'Code',
        'Code With Live',
        'Code With Live Analyzers',
        'Cognitive',
        'Cognitive AI',
        'Community',
        'Community Panel',
        'Community Panel Discussion',
        'Componentbased',
        'Componentbased Applications',
        'Components',
        'Components and More',
        'Components and More Effective',
        'Continuous',
        'Continuous Integration',
        'Continuous Integration and Deployment',
        'Core',
        'Core 1.0',
        'Core 1.0 and ASP',
        'Core data',
        'Core data protection',
        'Core everywhere',
        'Core everywhere else',
        'Couchbase',
        'Couchbase for .Net',
        'Couchbase for .Net Developers',
        'Create',
        'Create an Alexa',
        'Create an Alexa Skill',
        'Creation',
        'Creation from MVVM',
        'Creation from MVVM ViewModel',
        'CrossPlatform',
        'CrossPlatform Native',
        'CrossPlatform Native Awesomeness',
        'Curie',
        'Data',
        'Data Analysis',
        'Data Entry',
        'Data Entry Form',
        'Data Entry Form Creation',
        'Data Science',
        'Data Science applications',
        'Data and Hadoop',
        'Database',
        'Debugging',
        'Debugging with Microsoft',
        'Debugging with Microsoft Edge',
        'Delivery',
        'Deployment',
        'Designing',
        'Designing and Architecting',
        'Designing and Architecting Distributed',
        'DevOps',
        'DevOps C#',
        'DevOps C# and SQL',
        'DevOps Using Azure',
        'DevOps Using Azure DevTest',
        'DevOps to Optimize',
        'DevOps to Optimize Value',
        'DevTest',
        'DevTest Labs',
        'Developers',
        'Developers Attendees',
        'Developers Attendees chose',
        'Developing',
        'Developing for Mixed',
        'Developing for Mixed Reality',
        'Development',
        'Development With RiPi',
        'Different',
        'Different World',
        'Discussion',
        'Distributed',
        'Distributed Analytics',
        'Distributed Analytics and Data',
        'Distributed Caching',
        'ES2015',
        'ES2015 AngularJS',
        'ES2015 AngularJS 1.5.x',
        'ES2015 AngularJS 1.5.x Componentbased',
        'Edge',
        'Edge and Microsoft',
        'Edge and Microsoft Tools',
        'Effective',
        'Effective Angular',
        'Effective Angular 2',
        'Effective Angular 2 Testing',
        'Enterprise',
        'Enterprise Mobility',
        'Enterprise Mobility A Whole',
        'Entry',
        'Entry Form',
        'Entry Form Creation',
        'Evolved',
        'Evolved Reduxing',
        'Evolved Reduxing State',
        'Evolved Reduxing State Management',
        'Explore',
        'Explore Serverless',
        'Explore Serverless Architectures',
        'Fabric',
        'Felt',
        'Felt So',
        'Felt So Good',
        'FlatBuffers',
        'FlatBuffers all',
        'FlatBuffers all in One',
        'Form',
        'Form Creation',
        'Form Creation from MVVM',
        'Forms',
        'Forward',
        'Framework',
        'FrontEnd',
        'FrontEnd Debugging',
        'FrontEnd Debugging with Microsoft',
        'Functional',
        'Functional Techniques',
        'Functional Techniques for Imperative',
        'Functions',
        'GNU',
        'GNU for Data',
        'GNU for Data Analysis',
        'Get',
        'Get the most out',
        'Git',
        'Git A practical',
        'Git A practical guide',
        'Go',
        'Go CrossPlatform',
        'Go CrossPlatform Native',
        'Go CrossPlatform Native Awesomeness',
        'Good',
        'Great',
        'Great Team',
        'Great Team Starts',
        'Hadoop',
        'Handson',
        'Handson Labs',
        'Handson Labs Intel',
        'Handson Labs Intel Curie',
        'Hangfire',
        'Hangfire the ultimate',
        'Hangfire the ultimate MVC',
        'HoloLens',
        'IOT',
        'IOT to talk',
        'Imperative',
        'Imperative Object',
        'Imperative Object Oriented',
        'Imperative Object Oriented Languages',
        'Integration',
        'Integration and Deployment',
        'Intel',
        'Intel Curie',
        'Intro',
        'Intro to Visual',
        'Intro to Visual Web',
        'Introduction',
        'Introduction to Continuous',
        'Introduction to Continuous Integration',
        'Introduction to Microsoft',
        'Introduction to Microsoft Cognitive',
        'Introduction to R',
        'Introduction to Swift',
        'Introduction to Swift 3',
        'Introduction to dot Net',
        'Introduction to the SharePoint',
        'JavaScript',
        'JavaScript Evolved',
        'JavaScript Evolved Reduxing',
        'JavaScript Evolved Reduxing State',
        'Labs',
        'Labs Intel',
        'Labs Intel Curie',
        'Languages',
        'Lets',
        'Lets Build',
        'Lets Build a Bot',
        'Leveraging',
        'Leveraging UNIX',
        'Leveraging UNIX Tools',
        'Leveraging UNIX Tools GNU',
        'Live',
        'Live Analyzers',
        'MVC',
        'MVC and WebApi',
        'MVC and WebApi Task',
        'MVP',
        'MVP and Community',
        'MVP and Community Panel',
        'MVVM',
        'MVVM ViewModel',
        'Make',
        'Make your Mobile',
        'Make your Mobile App',
        'Management',
        'Management Objects',
        'Management Objects SMO',
        'Management with Angular',
        'Management with Angular 2',
        'Manager',
        'Maturing',
        'Maturing DevOps',
        'Maturing DevOps to Optimize',
        'Meatspace',
        'Megabytes',
        'Megabytes to Terabytes',
        'Megabytes to Terabytes quickly',
        'Metaprogramming',
        'Metaprogramming in dot Net',
        'Micro',
        'Micro controller',
        'Micro controller Setup',
        'Microsoft',
        'Microsoft Azure',
        'Microsoft Azure Functions',
        'Microsoft Cognitive',
        'Microsoft Cognitive AI',
        'Microsoft Edge',
        'Microsoft Edge and Microsoft',
        'Microsoft HoloLens',
        'Microsoft Tools',
        'Microsofts',
        'Microsofts AzureBigData',
        'Microsofts AzureBigData Technologies',
        'Mixed',
        'Mixed Reality',
        'Mixed Reality with Microsoft',
        'Mobile',
        'Mobile App',
        'Mobile App Stand',
        'Mobile App Stand Out',
        'Mobility',
        'Mobility A Whole',
        'Mobility A Whole Different',
        'Modern',
        'Modern jQuery',
        'Modern jQuery Refactoring',
        'Monads',
        'Monads as',
        'Monads as simple',
        'Monads as simple as',
        'Monitoring',
        'Monitoring in Meatspace',
        'More',
        'More Effective',
        'More Effective Angular',
        'More Effective Angular 2',
        'Native',
        'Native Awesomeness',
        'Never',
        'Never Felt',
        'Never Felt So',
        'Never Felt So Good',
        'Object',
        'Object Oriented',
        'Object Oriented Languages',
        'Objects',
        'Objects SMO',
        'One',
        'One hour',
        'Optimize',
        'Optimize Value',
        'Optimize Value Delivery',
        'Oriented',
        'Oriented Languages',
        'Out',
        'Panel',
        'Panel Discussion',
        'Part',
        'Part Development',
        'Pine64',
        'Pine64 Using Windows',
        'Pine64 Using Windows 10',
        'Practical',
        'Practical DevOps',
        'Practical DevOps Using Azure',
        'Programmable',
        'Programmable Programming',
        'Programming',
        'Programming Azure',
        'Programming Azure Service',
        'Programming Azure Service Fabric',
        'Programming for the CLR',
        'R',
        'Rapid',
        'Rapid XamarinForms',
        'Rapid XamarinForms XAML',
        'Rapid XamarinForms XAML Data',
        'Reality',
        'Reality with Microsoft',
        'Reality with Microsoft HoloLens',
        'Reasons',
        'Reasons to upgrade',
        'Reduxing',
        'Reduxing State',
        'Reduxing State Management',
        'Refactoring',
        'Refactoring and Testing',
        'RiPi',
        'RiPi and Pine64',
        'SEO',
        'SEO scaling',
        'SEO scaling all',
        'SMO',
        'SQL',
        'SQL Database',
        'SQL Server',
        'SQL Server 2016',
        'SQL Server 2016 Enterprise',
        'SQL Server Management',
        'SQL Server Management Objects',
        'Scale',
        'Scale dot Net',
        'Scale dot Net Apps',
        'Scaling',
        'Scaling Techniques',
        'Scaling Techniques for Azure',
        'Scaling Up',
        'Scaling Up going',
        'Science',
        'Science applications',
        'Science applications using Microsofts',
        'Securing',
        'Securing your Azure',
        'Securing your Azure Web',
        'Server',
        'Server 2016',
        'Server 2016 Enterprise',
        'Server Management',
        'Server Management Objects',
        'Server Management Objects SMO',
        'Serverless',
        'Serverless Architectures',
        'Serverless Architectures with Microsoft',
        'Service',
        'Service Fabric',
        'Services',
        'Services Workers',
        'Services Workers Your Web',
        'Setup',
        'Setup and Development',
        'SharePoint',
        'SharePoint Framework',
        'Skill',
        'So',
        'So Good',
        'Stand',
        'Stand Out',
        'Starts',
        'Starts With Youand',
        'State',
        'State Management',
        'State Management with Angular',
        'Strategies',
        'Studio',
        'Studio A look',
        'Studio A look at',
        'Swift',
        'Swift 3',
        'Swift Introduction',
        'Swift Introduction to Swift',
        'TSQL',
        'TSQL for Application',
        'TSQL for Application Developers',
        'Task',
        'Task Manager',
        'Team',
        'Team Starts',
        'Team Starts With Youand',
        'Techniques',
        'Techniques for Azure',
        'Techniques for Azure SQL',
        'Techniques for Imperative',
        'Techniques for Imperative Object',
        'Technologies',
        'Terabytes',
        'Terabytes quickly',
        'Testable',
        'Testable ES2015',
        'Testable ES2015 AngularJS',
        'Testable ES2015 AngularJS 1.5.x',
        'Testing',
        'Testing Strategies',
        'Testing the Way',
        'Testing the Way Forward',
        'Tools',
        'Tools GNU',
        'Tools GNU for Data',
        'UNIX',
        'UNIX Tools',
        'UNIX Tools GNU',
        'Understanding',
        'Understanding Azure',
        'Understanding Azure Service',
        'Understanding Azure Service Fabric',
        'Up',
        'Up going',
        'Up going from Megabytes',
        'Value',
        'Value Delivery',
        'ViewModel',
        'Visual',
        'Visual Studio',
        'Visual Studio A look',
        'Visual Web',
        'Visual Web Part',
        'Visual Web Part Development',
        'Way',
        'Way Forward',
        'Wearable',
        'Wearable Handson',
        'Wearable Handson Labs',
        'Wearable Handson Labs Intel',
        'Web',
        'Web App',
        'Web App with ASP',
        'Web Applications',
        'Web Applications Never',
        'Web Applications Never Felt',
        'Web Part',
        'Web Part Development',
        'WebApi',
        'WebApi Task',
        'WebApi Task Manager',
        'Who',
        'Who needs',
        'Who needs Visual',
        'Who needs Visual Studio',
        'Whole',
        'Whole Different',
        'Whole Different World',
        'Windows',
        'Windows 10',
        'Windows 10 IOT',
        'Workers',
        'Workers Your Web',
        'Workers Your Web Applications',
        'World',
        'Write',
        'Write Better',
        'Write Better C#',
        'Write Better C# Code',
        'XAML',
        'XAML Data',
        'XAML Data Entry',
        'XAML Data Entry Form',
        'Xamarin',
        'Xamarin Forms',
        'XamarinForms',
        'XamarinForms XAML',
        'XamarinForms XAML Data',
        'XamarinForms XAML Data Entry',
        'Xbox',
        'Xbox One',
        'Youand',
        'ZeroMQ',
        'ZeroMQ ZooKeeper',
        'ZeroMQ ZooKeeper and FlatBuffers',
        'ZooKeeper',
        'ZooKeeper and FlatBuffers',
        'ZooKeeper and FlatBuffers all',
        'all',
        'all in One',
        'all in One hour',
        'all in one',
        'applications',
        'applications using Microsofts',
        'applications using Microsofts AzureBigData',
        'as',
        'as it',
        'as simple',
        'as simple as',
        'as simple as it',
        'at',
        'at using dot net',
        'azure',
        'azure creation',
        'azure creation debugging',
        'azure creation debugging SEO',
        'build',
        'build games',
        'build games on Xbox',
        'chose',
        'controller',
        'controller Setup',
        'controller Setup and Development',
        'creation',
        'creation debugging',
        'creation debugging SEO',
        'creation debugging SEO scaling',
        'danger',
        'data',
        'data protection',
        'debugging',
        'debugging SEO',
        'debugging SEO scaling',
        'debugging SEO scaling all',
        'dot net',
        'dot net Apps',
        'dot net Core',
        'dot net Core 1.0',
        'dot net Core data',
        'dot net Core everywhere',
        'dot net Developers',
        'else',
        'everywhere',
        'everywhere else',
        'games',
        'games on Xbox',
        'games on Xbox One',
        'going',
        'going from Megabytes',
        'guide',
        'guide for the rest',
        'hidden',
        'hidden danger',
        'hour',
        'it',
        'jQuery',
        'jQuery Refactoring',
        'jQuery Refactoring and Testing',
        'look',
        'look at',
        'needs',
        'needs Visual',
        'needs Visual Studio',
        'one',
        'out',
        'out of Xamarin',
        'out of Xamarin Forms',
        'practical',
        'practical guide',
        'protection',
        'quickly',
        'rest',
        'scaling',
        'scaling all',
        'scaling all in one',
        'simple',
        'simple as',
        'simple as it',
        'talk',
        'talk to AndroidLinux',
        'ultimate',
        'ultimate MVC',
        'ultimate MVC and WebApi',
        'upgrade',
        'upgrade to SQL',
        'upgrade to SQL Server',
        'websites',
        'websites on azure',
        'websites on azure creation'
    ],

    moreCompleteSessionPhrases: function () {
        return this.sessionPhrases.filter(function (phrase) {
            // return phrases that have at least three words (two spaces or more)
            return (phrase.match(/ /g) || []).length >= 2;
        });
    // },
    // Step 5: Format the spoken text
    // mostPopularSpeaker: function (name, inquiries) {
    //     return 'The most popular speaker is ' + name + ' with ' + inquiries.toString() + ' inquiries.';
    }
};

module.change_code = 1;
module.exports = textHelper;
